name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    environment: NuGet.org
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune origin +refs/heads/master:refs/remotes/origin/master
        git merge-base --is-ancestor "$GITHUB_SHA" origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push GitHub
      run: dotnet nuget push Pipeliner.Net.${VERSION}.nupkg --source https://nuget.pkg.github.com/emcrank/index.json --api-key "${GIT_APIKEY}"
      env:
        GIT_APIKEY: ${{ secrets.GIT_APIKEY }}
    - name: Push NuGet
      run: dotnet nuget push Pipeliner.Net.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key "${NUGET_APIKEY}"
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}